# 工作流名称
name: 每8个小时更新一次reference

# 触发工作流的事件
on:
  schedule:
    # - cron: '0 */8 * * *' # 每8小时运行一次（在每天的 0:00, 8:00, 16:00 UTC）
    - cron: '*/5 * * * *'
  workflow_dispatch:  # 允许手动触发工作流

# 定义工作流中的作业
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout forked repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Sync with upstream
      run: |
        git remote add upstream https://github.com/jaywcjlove/reference.git
        git fetch upstream
        git merge upstream/main --no-edit || true
        
    - name: Push changes
      run: |
        git push origin main || git push --force origin main

    - name: Check for changes
      run: |
        if git status | grep -q "Your branch is up to date"; then
          echo "No changes to push."
        else
          echo "Changes were pushed to the repository."
        fi
